
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup node js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm install

    - name: Start frontend server
      run: npm run dev &
      
    - name: Wait for frontend server to be ready
      run: |
        for i in {1..20}; do
          if curl -s http://localhost:5173 > /dev/null; then
            echo "Frontend is up!"
            exit 0
          fi
          echo "Waiting for frontend..."
          sleep 3
        done
        echo "Frontend did not start in time"
        exit 1

  
  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy-scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '5m'
          output: 'trivy-report.txt'
      - name: read trvy report
        run: |
          if grep -q "CRITICAL\|HIGH" trivy-report.txt; then
            echo "Vulnerabilities found, creating github issue..."
            gh issue create  \
              --title "Trivy Scan: Vulnerabilities detected" \
              --body "$(cat trivy-report.txt)" \
              --label "security" 
          else
            echo "No critical or high vulnerabilities found ✅"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


